### PR TITLE
Use rvm if available

### LINKED ISSUE #66: Can't get SublimeLinter-rubocop 3.0.0 running with rvm
Hi,

after searching for the reason SL-R doesn't work anymore for me I noticed the version bump.
It also took me some more time to find the notes in the "Release"-section (a package-control notice would have been really nice).

So, since that I try to get it working again and ... keep on failling.

I added the following in my ~/.config/sublime-text-3/Packages/User/SublimeLinter.sublime-settings
```
    "linters": {
      "rubocop": {
        "executable": ["~/.rvm/rubies/default/bin/ruby", "-S", "rubocop"]
      }
    },
```

Manually running

cat path/to/my.rb | /home/me/.rvm/rubies/default/bin/ruby -S rubocop --format emacs --force-exclusion --stdin /full/path/to/my.rb

on terminal works fine. But the SublimeText console debug output is:

```
SublimeLinter: sublime_linter.py:266  Delay linting 'my.rb' for 0.0s
SublimeLinter: linter.py:985          rubocop: checking lint mode 'background' vs lint reason 'on_user_request'
SublimeLinter: #11 linter.py:1003     rubocop: linting 'my.rb'
SublimeLinter: #11 linter.py:786      rubocop: wanted executable is '['/home/me/.rvm/rubies/default/bin/ruby', '-S', 'rubocop']'
SublimeLinter: #11 linter.py:1478     Running ...

  /home/me/<path_to>/backend  (working dir)
  $ cat path/to/my.rb | /home/me/.rvm/rubies/default/bin/ruby -S rubocop --format emacs --force-exclusion --stdin  /full/path/to/my.rb

SublimeLinter: #11 linter.py:684      WARNING: rubocop output:
/home/me/.rvm/rubies/default/bin/ruby: No such file or directory -- rubocop (LoadError)

SublimeLinter: #11 linter.py:686      Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: #11 linter.py:1076     rubocop: no output
SublimeLinter: sublime_linter.py:529  Linting 'my.rb' took 0.10s
```

And my statusbar says "rubocop(erred)".

What am I missing, what am I doing wrong?

Thanks for any help!

Working on:
* Ubuntu 18.04.2 LTS
* rvm ruby 2.6.3
* rubocop 0.70.0
* Sublime Text Build 3208

Edit: I have serveral projects on my machines with different rubies, so I am forced to get a "generic" rvm ruby detection running.

### PR DESCRIPTION
**Pull request by kaste**
Fixes #66

Remember: I don't have 'rvm' and can't test this, so any typo can break.

### CODE REVIEW

**Comment by braver** [comment]
I can’t test either, and no one in the community will. Two possible courses of action:

1. push the change, see if anyone bothers to report the breakage, if any.
2. close the PR. If no one in the community can be bothered to test the solution, the problem seems to be unimportant.

What do you wan to do? I vote no. 2.

**Comment by katzer** [comment]
I am using RVM. How to install the plugin based on this PR?

**Comment by kaste** [comment]
Hi @katzer! Just clone the repo and checkout the PR into your Packages folder. (into this one `Preferences > Browse Packages`)

**Comment by katzer** [comment]
It works!

**Comment by katzer** [comment]
I noticed that my root problem was that ST did not load my profile and correct `PATH`. Since its loading the login shell, there needs to be a `~/.zlogin`, `~/bash_login`, ... file. Other files like `~/zshrc` or `.bashrc` won't work.

**Comment by kaste** [comment]
No risk no fun merge

**Pull request merged**
