### PR TITLE
Moved syntax attribute to use 'defaults'

### PR DESCRIPTION
**Pull request by 1dustindavis**
Addresses #58 by replacing the `syntax` attribute with a `selector` within the defaults attribute as defined here: http://www.sublimelinter.com/en/stable/linter_settings.html#selector

### CODE REVIEW

**Comment by braver** [comment]
Thanks! Looks good to me. @kaste agree?

**Comment by kaste** [comment]
Yeah, definitely looks good to me. Thanks!

**Comment by braver** [comment]
Probably. What is the root scope of such a file?

**Comment by braver** [comment]
What does it say when you run "Show Scope Name" in one of those files?

screen shot 2018-07-02 at 13 38 23

**Comment by fschwahn** [comment]
```
text.html.ruby text.html.basic source.ruby.rails.embedded.html punctuation.definition.group.end.ruby
```

**Pull request merged**
